### ISSUE TITLE
when opening a compare window i constantly get an exception

### ISSUE THREAD

**Issue by jcompagner** [eclipse/lsp4e#10]
!MESSAGE An internal error occurred during: "LSP4E Linked Editing Highlight".
!STACK 0
java.lang.NullPointerException: Cannot enter synchronized block because the return value of "org.eclipse.lsp4e.operations.linkedediting.LSPLinkedEditingReconcilingStrategy.getLockObject(org.eclipse.jface.text.source.IAnnotationModel)" is null
	at org.eclipse.lsp4e.operations.linkedediting.LSPLinkedEditingReconcilingStrategy.updateLinkedEditingAnnotations(LSPLinkedEditingReconcilingStrategy.java:230)
	at org.eclipse.lsp4e.operations.linkedediting.LSPLinkedEditingReconcilingStrategy.lambda$2(LSPLinkedEditingReconcilingStrategy.java:196)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

I use WWD that has an LSP4E version: 	0.13.7.202111051530	

It happens with pretty much every file that is i guess related to a language server file (like ts files but also package.json files)

**Comment by mickaelistria** [comment]
Duplicates #3

**Comment by jcompagner** [comment]
hmm should have checked the closed :(
