### ISSUE TITLE
Unclear "Internal error."

### ISSUE THREAD

**Issue by laeubi** [eclipse/lsp4e#101]
I see this in the error log:

```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$13(LanguageServerWrapper.java:425)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$4(LanguageServerWrapper.java:260)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

beside the error occurring, it gives no information about the cause of the "internal error" so its hard to ges whats the problem here

**Comment by mickaelistria** [comment]
I think this is more an issue in LSP4J failing at surfacing the root issue. IIRC, I sometimes saw this stack for malformed LSP messages (not conform to the protocol, or using newer protocol constructs not yet suppored by LSP4J) that LSP4J wasn't able to deserialize.
Do you have steps to reproduce this issue? Can you try enabling logging in LSP4E to see the messages and maybe find out one that triggers this error?

**Comment by laeubi** [comment]
> I think this is more an issue in LSP4J failing at surfacing the root issue.

Posssible you could transfer the issue if you think it better fits lsf4j

> Do you have steps to reproduce this issue?

No I just looked into the error log because of some other issues and though it would be good to report it.

> that LSP4J wasn't able to deserialize.

Thats what I think should be improved, e.g adding something like "message could not be deserialized: [some internal error message?]"

**Comment by mickaelistria** [comment]
I'm not a maintainer on LSP4J so I cannot transfer the issue. Would you mind re-reporting it there?

**Comment by sebthom** [comment]
Closing the issue as this is not an issue in LSP4E. Feel free to reopen in case of additional context information and stacktraces of a recent LSP4J/LSP4E release.
