### ISSUE TITLE
Errors when creating untitled text files

### ISSUE THREAD

**Issue by PyvesB** [eclipse/lsp4e#147]
Hello 👋🏻 

When creating an untitled text file in Eclipse, the following error is now thrown by LSP4E, and the resulting file can no longer be saved:
```
org.eclipse.core.runtime.CoreException: File not found: <workspace>/.metadata/.plugins/org.eclipse.ui.editors/_1727503488.
	at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:48)
	at org.eclipse.core.internal.filesystem.local.LocalFile.openInputStream(LocalFile.java:423)
	at org.eclipse.core.internal.filebuffers.FileStoreTextFileBuffer.getContentType(FileStoreTextFileBuffer.java:293)
	at org.eclipse.lsp4e.LSPEclipseUtils.getDocumentContentTypes(LSPEclipseUtils.java:934)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLSWrappers(LanguageServiceAccessor.java:348)
	at org.eclipse.lsp4e.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:601)
	at org.eclipse.lsp4e.operations.rename.LSPRenameHandler.setEnabled(LSPRenameHandler.java:113)
	at org.eclipse.ui.internal.handlers.HandlerProxy.setEnabled(HandlerProxy.java:229)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.canExecute(E4HandlerProxy.java:76)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.isEnabled(HandlerServiceHandler.java:62)
	at org.eclipse.core.commands.Command.isEnabled(Command.java:832)
	at org.eclipse.ui.menus.CommandContributionItem.isEnabled(CommandContributionItem.java:917)
	at org.eclipse.ui.menus.CommandContributionItem.updateMenuItem(CommandContributionItem.java:531)
	at org.eclipse.ui.menus.CommandContributionItem.update(CommandContributionItem.java:484)
	at org.eclipse.ui.menus.CommandContributionItem.update(CommandContributionItem.java:477)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$0(CommandContributionItem.java:935)
	at org.eclipse.jface.bindings.BindingManager.fireBindingManagerChanged(BindingManager.java:901)
	at org.eclipse.jface.bindings.BindingManager.setActiveBindings(BindingManager.java:2181)
	at org.eclipse.jface.bindings.BindingManager.recomputeBindings(BindingManager.java:1742)
	at org.eclipse.jface.bindings.BindingManager.contextManagerChanged(BindingManager.java:691)
	at org.eclipse.core.commands.contexts.ContextManager.fireContextManagerChanged(ContextManager.java:164)
	at org.eclipse.core.commands.contexts.ContextManager.setEventCaching(ContextManager.java:323)
	at org.eclipse.core.commands.contexts.ContextManager.deferUpdates(ContextManager.java:85)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:778)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:680)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:675)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3215)
	at org.eclipse.ui.internal.WorkbenchPage.lambda$9(WorkbenchPage.java:3097)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3095)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3065)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3048)
	at org.eclipse.ui.internal.editors.text.UntitledTextFileWizard.performFinish(UntitledTextFileWizard.java:79)
	at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:127)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4579)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4365)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3941)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: java.io.FileNotFoundException: <workspace>/.metadata/.plugins/org.eclipse.ui.editors/_1727503488 (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.eclipse.core.internal.filesystem.local.LocalFile.openInputStream(LocalFile.java:418)
	... 68 more
```

I'm using LSP4E 0.13.12.202206011407, as far as I can tell this regression was introduced in the last few days.

**Comment by jonahgraham** [comment]
I was able to get same stack trace in SimRel 2022-06 RC1 which contains the mentioned LSP4E version, but I was still able to save the file\*. In addition to the stack trace above I see the below message in the log which may help track it down:

```
!ENTRY org.eclipse.lsp4e 4 0 2022-06-03 19:04:13.867
!MESSAGE Exception occurred while fetching the content type from the buffer
!STACK 1
org.eclipse.core.runtime.CoreException: File not found: /tmp/a/data/.metadata/.plugins/org.eclipse.ui.editors/_851316413.
```

However I also get the same exception logged with 2022-03, but not 2021-12. 

While I think this exception is noisy and probably can be suppressed in some cases, I think the behaviour it of the IDE is still correct.

\* *Note that you can only save the untitled text file once you make it dirty - that behaviour is consistent with older versions of Eclipse.*

Am I missing something?

(All my tests done with my C/C++ EPP package)

**Comment by GeraldMit** [comment]
I also inadvertently ran up against this today _File->New->Other->General->Untitled Text File_  which results in multiple 'Exception occurred while fetching the content type  from the buffer errors' logged in the error log.

> !ENTRY org.eclipse.lsp4e 4 0 2022-08-12 17:52:47.757
> !MESSAGE Exception occurred while fetching the content type from the buffer
> !STACK 1
> org.eclipse.core.runtime.CoreException: File not found: /Users/geraldmit/runtime-geraldmit/.metadata/.plugins/org.eclipse.ui.editors/_812893209.
> 	at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:48)
> 	at org.eclipse.core.internal.filesystem.local.LocalFile.openInputStream(LocalFile.java:423)
> 	at org.eclipse.core.internal.filebuffers.FileStoreTextFileBuffer.getContentType(FileStoreTextFileBuffer.java:293)
> 	at org.eclipse.lsp4e.LSPEclipseUtils.getDocumentContentTypes(LSPEclipseUtils.java:934)
> 	at org.eclipse.lsp4e.LanguageServersRegistry.canUseLanguageServer(LanguageServersRegistry.java:442)
> 	at org.eclipse.lsp4e.HasLanguageServerPropertyTester.test(HasLanguageServerPropertyTester.java:34)
> 	at org.eclipse.core.internal.expressions.Property.test(Property.java:65)
> 	at org.eclipse.core.expressions.TestExpression.evaluate(TestExpression.java:107)
> 	at org.eclipse.core.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:54)
> 	at org.eclipse.core.expressions.WithExpression.evaluate(WithExpression.java:84)
> ...
> Caused by: java.io.FileNotFoundException: /Users/geraldmit/runtime-geraldmit/.metadata/.plugins/org.eclipse.ui.editors/_812893209 (No such file or directory)
> 	at java.base/java.io.FileInputStream.open0(Native Method)
> 	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
> 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
> 	at org.eclipse.core.internal.filesystem.local.LocalFile.openInputStream(LocalFile.java:418)
> 	... 138 more


error is valid, but based  on what is going on (contentType assessment), I think maybe just the error doesn't need to be logged?

**Comment by GeraldMit** [comment]
Looking in the stack the LSP should probably quietly fail, it is being evaluative to see if it is relevant to the event in these cases.

In the untitled file case there *is* no contentType possible as the file doesn't exist and has 0 bytes.  
if the file had a name that was a registered name type like example.js  the ContentType is determined from the registered extension if not through the buffer and is still correct.
```
if (e.getCause() instanceof java.io.FileNotFoundException) {
//origin is IFile res = ResourcesPlugin.getWorkspace().getRoot().getFile(path); where (res == null || !res.exists())
//Backing for document may no longer exist, have never existed, been temporary or transient, not representable by an IFile due to location, unaccessible via a lock or remote connection, or have 0 bytes content
//The content type may still be based on path or file name pattern or another subsystem via the ContentTypeManager so this is not an error condition
} else {
//account for some other unknown CoreException
LanguageServerPlugin.logError("Exception occurred while fetching the content type from the buffer", e); //$NON-NLS-1$;
}
```
