### ISSUE TITLE
"DebugException: Terminate failed" thrown when a debugged program ends normally

### ISSUE THREAD

**Issue by sebthom** [eclipse/lsp4e#264]
When running a ([Dart](https://github.com/dart4e/dart4e) or [Haxe](https://github.com/haxe4e/haxe4e)) program in DAP debug mode and it ends normally on it's own I am always seeing the following exception in the log:
```python
org.eclipse.debug.core.DebugException: Terminate failed
	at org.eclipse.debug.core.model.RuntimeProcess.terminate(RuntimeProcess.java:259)
	at org.eclipse.lsp4e.debug.launcher.DSPLaunchDelegate.lambda$1(DSPLaunchDelegate.java:313)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.terminated(DSPDebugTarget.java:318)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.terminated(DSPDebugTarget.java:366)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4e.debug.debugmodel.DSPDebugTarget.lambda$1(DSPDebugTarget.java:174)
	at org.eclipse.lsp4j.jsonrpc.validation.ReflectiveMessageValidator.consume(ReflectiveMessageValidator.java:68)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I tried to fix it by naively changing the cleanup callback from:
https://github.com/eclipse/lsp4e/blob/3702e57e364d9acaebbb3e33d8b806f8da0b7e41/org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/launcher/DSPLaunchDelegate.java#L311-L318
to
```java
cleanup = () -> {
	try {
		if (!debugAdapterIProcess.isTerminated()) {
			debugAdapterIProcess.terminate();
		}
		debugAdapterProcess.destroy();
	} catch (DebugException e) {
		DSPPlugin.logError(e);
	}
};
```
but the error persists. Apparently `debugAdapterIProcess.isTerminated()` does not take into account that the process can end on it's own, i.e. does not represent the live state but only returns the value of an internal boolean `fTerminated`.

@jonahgraham any thoughts on this?

**Comment by jonahgraham** [comment]
Sadly when I wrote the first version of this code it never got past the "WIP" state (ef8397e05822334b473d8ad7a440475ba274151e). The terminating condition was probably not well thought out as it wasn't needed to make demos of debug adapter in Eclipse look good.

Firstly, the `cleanup` code is actually run while the debug adapter is still running. If you put a breakpoint in the `cleanup` code you will see the dart debug adapter is still running in your OS task list.

What is needed here is a bigger fix to account for the fact that debug adapter can terminate cleany, and when they do they send an [exited event.](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Exited) The LSP4E implementation here is "rude" and terminates the process as soon as it receives the terminated event.

Something like this is probably better, but needs some thought + exercising. (Keeping in mind the fix in a340bcc6312ec41a832ea8290c80f14bf5a72bb2 for debug adapters that don't exit nicely on their own - which by the way not sure why `destroyForcibly` wasn't applied to the monitor case)

The reason the `debugAdapterIProcess.terminate()` fails to terminate the debug adapter is because the code in `RuntimeProcess` is supposed to wait 5 seconds (RuntimeProcess.TERMINATION_TIMEOUT) after issuing the `Process.destroy()`. However the RuntimeProcess does not do that because the current thread has the `interrupted` flag set, which means as soon as `waitFor` is called, an `InterruptedException` is immediately raised, which has the same behaviour as the timeout.

The thread is in the `interrupted` state because of:

https://github.com/eclipse/lsp4e/blob/3702e57e364d9acaebbb3e33d8b806f8da0b7e41/org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java#L306

This is how LSP4J shuts down its listening thread. But the listening thread is the current thread, so there is nothing waiting that needs to be interrupted. We can't pass false here as that would prevent the message loop from shutting down. Therefore I propose that we simply clear the interrupt flag.

I will provide a PR for the simple case and raise an issue for the fix of not killing the debug adapter on receipt of `terminated` event. The fix for this simple case is needed regardless, as the cancel call will just move later in time, but is still needed.
