### ISSUE TITLE
Refactoring TS variable may throw error

### ISSUE THREAD

**Issue by AndrewFerr** [eclipse/lsp4e#309]
On the latest snapshot release (0.15.0.202211181007), refactoring (renaming) a variable in a TS file may fail with this error:
> An unexpected exception occurred while creating a change object. See the error log for more details.

The Error Log shows the stack trace of the error having come from `org.eclipse.ltk.ui.refactoring`:
```
java.lang.reflect.InvocationTargetException
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:93)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.eclipse.core.runtime.CoreException: new rename cannot be null
	at org.eclipse.lsp4e.operations.rename.LSPRenameProcessor.createChange(LSPRenameProcessor.java:196)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.createChange(ProcessorBasedRefactoring.java:290)
	at org.eclipse.ltk.core.refactoring.CreateChangeOperation.run(CreateChangeOperation.java:125)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:89)
	... 1 more
```

This happens in a clean workspace on a newly-created project.  It happens whether the project has a `tsconfig.json` file or not.

I haven't been able to reproduce this for JS files.

**Comment by AndrewFerr** [comment]
Updated, and it looks like it works!  Thanks for the fixes!

**Comment by mickaelistria** [comment]
Thanks would go to @vrubezhny for the fixes, and you for testing ;)
