### ISSUE TITLE
NPE when clicking on XSD link on XML tag hover

### ISSUE THREAD

**Issue by fbricon** [eclipse/lsp4e#335]
Using latest Eclipse 2022-12, if you open a pom.xml file, hover over any tag, documentation pops up, with a link to the maven-4.0.0.xsd schema at the bottom (when using the dark theme, if you squint your eyes, you'll be able to read the name, but that's [another topic](https://github.com/eclipse/lsp4e/issues/108#issuecomment-1344128243)). 
<img width="545" alt="Screenshot 2022-12-09 at 11 09 04" src="https://user-images.githubusercontent.com/148698/206678200-5c2709f5-fa72-4fd5-8ba6-a0be4a094eda.png">

If you click on the link, nothing happens, an error is logged:

```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1149)
        at org.eclipse.lsp4e.LSPEclipseUtils.parseRange(LSPEclipseUtils.java:606)
        at org.eclipse.lsp4e.LSPEclipseUtils.open(LSPEclipseUtils.java:579)
        at org.eclipse.lsp4e.LSPEclipseUtils.open(LSPEclipseUtils.java:567)
        at org.eclipse.lsp4e.LSPEclipseUtils.open(LSPEclipseUtils.java:563)
        at org.eclipse.lsp4e.operations.hover.FocusableBrowserInformationControl$1.changing(FocusableBrowserInformationControl.java:52)
        at org.eclipse.swt.browser.WebKit.webView_decidePolicyForNavigationAction_request_frame_decisionListener(WebKit.java:1499)
        at org.eclipse.swt.browser.WebKit.browserProc(WebKit.java:419)
        at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
        at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:236)
        at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2264)
        at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2511)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:6444)
        at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
        at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5692)
        at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5831)
        at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
        at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:117)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3986)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

The maven-4.0.0.xsd file should open.

**Comment by mickaelistria** [comment]
@bastiandoetsch It looks like a regression from https://github.com/eclipse/lsp4e/commit/f1aebc0b89a7eca7eec7e7fb8adfd37e48881675 . Can you please investigate?

**Comment by bastiandoetsch** [comment]
Yeah, if the fragment is empty/null, this NPE occurs. Will provide a PR asap.

**Comment by bastiandoetsch** [comment]
Seems like one of the (untouched) tests runs into a timeout: https://ci.eclipse.org/lsp4e/job/lsp4e-github/job/PR-336/1/testReport/junit/org.eclipse.lsp4e.test.highlight/HighlightTest/testCheckIfOtherAnnotationsRemains/
