### ISSUE TITLE
Got an error when setup development with Oomph

### ISSUE THREAD

**Issue by ghentschke** [eclipse/lsp4e#511]
I am on a windows machine and get the following error when updating my workspace setup:

```
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:919)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1677751388716
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1677751388716 requires 'osgi.bundle; org.eclipse.lsp4j [0.20.0.v20230216-1815,0.20.0.v20230216-1815]' but it could not be found
```
This is my workspace setup:
![image](https://user-images.githubusercontent.com/123444711/222397872-3b577e23-4520-4cf5-b471-db7ce867f855.png)

I updated the Oomph installer, but the issue remains

**Comment by mickaelistria** [comment]
I don't think Oomph is supported to developer LSP4E. Please see https://github.com/eclipse/lsp4e/blob/master/CONTRIBUTING.md#%EF%B8%8F-setting-up-the-development-environment-manually

**Comment by ghentschke** [comment]
Setting up a new IDE and workspace fixed the issue
