### ISSUE TITLE
didOpen/didChange/didClose not sent, document not connected, if LS only provides diagnostics

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/lsp4e#560]
After upgrading to LSP4E v.0.22.0 WWD [ESLint LS Client has stopped working](https://github.com/eclipse/wildwebdeveloper/issues/1133#top).

It turns out that  the method `org.eclipse.wildwebdeveloper.eslint.ESLintClientImpl.configuration(ConfigurationParams)` is never been invoked during the initialization while the `configuration` capability is set to true.

When WWD rolling back to using LSP4E to [v.0.21.0](https://download.eclipse.org/lsp4e/releases/0.21.0/) ESLint LS works as expected: [see the proof](https://github.com/eclipse/wildwebdeveloper/pull/1138).

**Comment by wesleybl** [comment]
@vrubezhny In version `0.21.0`, `configuration` was already `True`. This was done in PR #256. So I'm not sure if this is the reason. @sebthom  can you help here? See WWD's ESLint client:

https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintClientImpl.java

**Comment by vrubezhny** [comment]
Problem is that after the release of LSP4E v.0.22.0 was picked up by WWD, the ESLint LS has stopped working. When  I'm rolling back WWD to use LSP4E v.0.21.0 the ESLint LS functionality restores.

The problem I see by debugging WWD, when I open a JS-file in editor, ESLint LS cannot be initialized properly - after ESLintClientImpl is created, its 'ESLintClientImpl.configuration(ConfigurationParams)` method is never invoked, so ESLint LS doesn't get configured properly.

**Comment by sebthom** [comment]
The code was refactored as part of #475 

The configuration now lives here:
https://github.com/eclipse/lsp4e/blob/12f6b4140daa8bf415c2bf8123b9ddd25bffc3a3/org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/SupportedFeatures.java#L122

And is applied via 
https://github.com/eclipse/lsp4e/blob/12f6b4140daa8bf415c2bf8123b9ddd25bffc3a3/org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java#L329-L334

From just going through that commit, the code change looks fine to me. So I am not sure if this is the culprit.

**Comment by sebthom** [comment]
I tested the code from master with the dart LSP and it works as expected:
```js
CLIENT >> {"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":32604,"rootPath":"/D:/dart-hotreloader/","rootUri":"file:///D:/dart-hotreloader/","initializationOptions":{"flutterOutline ":false,"suggestFromUnimportedLibraries":true},"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true,"configuration":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["markdown","plaintext"],"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"insertTextModeSupport":{"valueSet":[1,2]}}},"hover":{"contentFormat":["markdown","plaintext"]},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{},"definition":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"resolveSupport":{"properties":["edit"]},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{"prepareSupport":true},"foldingRange":{},"inlayHint":{}},"window":{"workDoneProgress":true,"showMessage":{},"showDocument":{"support":true}}},"clientInfo":{"name":"Eclipse IDE","version":"0.16.1.qualifier"},"trace":"off","workspaceFolders":[{"uri":"file:///D:/dart-hotreloader/","name":"dart-hotreloader"}]}}
CLIENT >> {"jsonrpc":"2.0","method":"initialized","params":{}}
...
SERVER >> {"id":1,"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///D:/dart-hotreloader","section":"dart"},{"section":"dart"}]}}
```

**Comment by sebthom** [comment]
Yes, I am testing it via a launch configuration that uses the master branch which includes that commit:
![image](https://user-images.githubusercontent.com/426959/226353153-9a95762a-f650-4549-817b-fc27c076dd1e.png)

I enabled step debugging and can see that code with that change gets invoked:
![image](https://user-images.githubusercontent.com/426959/226353640-8246d12f-f740-4ea5-a51e-581592516368.png)

**Comment by vrubezhny** [comment]
@sebthom could you please attach the full log from your test  with Dart LS between `CLIENT: ..."initialized"` and `SERVER: ..."workspace/configuration"` or better the full log? 
Looks like I'm missing something - it looks vscode uses the same "workspace/configuration" API to read and send the configuration to the server - but in our case the server doesn't requests it. So, probably it's out client's fault or missing some protocol steps during the initialization lead to this failure.

**Comment by sebthom** [comment]
here you go:
```js
CLIENT >> Content-Length: 1956
SERVER >> Content-Length: 1898
SERVER >> Content-Type: application/vscode-jsonrpc; charset=utf-8
CLIENT >> {"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":33752,"rootPath":"/D:/dart-hotreloader/","rootUri":"file:///D:/dart-hotreloader/","initializationOptions":{"flutterOutline ":false,"suggestFromUnimportedLibraries":true},"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true,"configuration":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["markdown","plaintext"],"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"insertTextModeSupport":{"valueSet":[1,2]}}},"hover":{"contentFormat":["markdown","plaintext"]},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{},"definition":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"resolveSupport":{"properties":["edit"]},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{"prepareSupport":true},"foldingRange":{},"inlayHint":{}},"window":{"workDoneProgress":true,"showMessage":{},"showDocument":{"support":true}}},"clientInfo":{"name":"Eclipse IDE","version":"0.16.1.qualifier"},"trace":"off","workspaceFolders":[{"uri":"file:///D:/dart-hotreloader/","name":"dart-hotreloader"}]}}Content-Length: 52
CLIENT >> {"jsonrpc":"2.0","method":"initialized","params":{}}Content-Length: 5248
CLIENT >> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///D:/dart-hotreloader/test/hotreloader_test.dart","languageId":"dart","version":1,"text":"/**\r\n * Copyright 2020-2022 by Vegard IT GmbH (https://vegardit.com) and contributors.\r\n * SPDX-License-Identifier: Apache-2.0\r\n *\r\n * @author Sebastian Thomschke, Vegard IT GmbH\r\n */\r\nimport \u0027dart:async\u0027;\r\nimport \u0027dart:io\u0027 as io;\r\nimport \u0027dart:isolate\u0027;\r\n\r\nimport \u0027package:hotreloader/hotreloader.dart\u0027;\r\nimport \u0027package:logging/logging.dart\u0027 as logging;\r\n\r\nimport \u0027reloadable.dart\u0027 as reloadable;\r\n\r\nfinal log \u003d new logging.Logger(\u0027hotreloader.test\u0027);\r\n\r\nFuture\u003cvoid\u003e _writeReloadableDartFile([String content \u003d \"String testfunc() \u003d\u003e \u0027foo\u0027;\"]) async {\r\n  // waiting for two seconds so that the modification timestamp will be different on\r\n  // filesystems with seconds-only precision\r\n  await Future\u003cvoid\u003e.delayed(const Duration(seconds: 2));\r\n  final dartFile \u003d new io.File(\u0027test/reloadable.dart\u0027);\r\n  log.info(\u0027Writing to [${dartFile.path}]: $content\u0027);\r\n  await dartFile.writeAsString(content, flush: true);\r\n}\r\n\r\n/* cannot use \"pub run test\" with hot reload as it results in:\r\n * kernel-service: Error: Unhandled exception:\r\n * Bad state: No element\r\n * #0      Iterable.first (dart:core/iterable.dart:520:7)\r\n * #1      MappedIterable.first (dart:_internal/iterable.dart:374:31)\r\n * #2      lookupOrBuildNewIncrementalCompiler (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:400:45)\r\n * #3      _processLoadRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:679:22)\r\n * #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)\r\n *\r\n * Unhandled exception:\r\n * Bad state: No element\r\n * #0      Iterable.first (dart:core/iterable.dart:520:7)\r\n * #1      MappedIterable.first (dart:_internal/iterable.dart:374:31)\r\n * #2      lookupOrBuildNewIncrementalCompiler (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:400:45)\r\n * #3      _processLoadRequest (file:///C:/b/s/w/ir/cache/builder/sdk/pkg/vm/bin/kernel_service.dart:679:22)\r\n * #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)\r\n */\r\nFuture\u003cvoid\u003e main() async {\r\n  logging.hierarchicalLoggingEnabled \u003d true;\r\n  logging.Logger.root.onRecord.listen((record) \u003d\u003e print(// ignore: avoid_print\r\n      \u0027${record.time} ${record.level.name} [${Isolate.current.debugName}] ${record.loggerName}: ${record.message}\u0027 //\r\n      ));\r\n\r\n  HotReloader.logLevel \u003d logging.Level.FINEST;\r\n\r\n  await testProgrammaticReload();\r\n  await testAutomaticReload();\r\n\r\n  log.info(\u0027*** ALL TESTS COMPLETED.***\u0027);\r\n  io.exit(0);\r\n}\r\n\r\nFuture\u003cvoid\u003e testProgrammaticReload() async {\r\n  log.info(\u0027TEST: test_programmatic_reload...\u0027);\r\n\r\n  var callbacksTriggered \u003d 0;\r\n  final hotreloader \u003d await HotReloader.create(\r\n    automaticReload: false,\r\n    // ignore: avoid_redundant_argument_values\r\n    debounceInterval: Duration.zero, //\r\n    onBeforeReload: (ctx) {\r\n      callbacksTriggered++;\r\n      return true;\r\n    },\r\n    onAfterReload: (ctx) {\r\n      callbacksTriggered++;\r\n    }\r\n  );\r\n\r\n  try {\r\n    assert(reloadable.testfunc() \u003d\u003d \u0027foo\u0027);\r\n    await _writeReloadableDartFile(\"String testfunc() \u003d\u003e \u0027bar\u0027;\");\r\n\r\n    // perform programmatic code reload\r\n    assert(await hotreloader.reloadCode() \u003d\u003d HotReloadResult.Succeeded);\r\n    assert(reloadable.testfunc() \u003d\u003d \u0027bar\u0027);\r\n    assert(callbacksTriggered \u003d\u003d 2);\r\n  } finally {\r\n    // restore initial state\r\n    await _writeReloadableDartFile();\r\n    assert(await hotreloader.reloadCode() \u003d\u003d HotReloadResult.Succeeded);\r\n    assert(reloadable.testfunc() \u003d\u003d \u0027foo\u0027);\r\n\r\n    await hotreloader.stop();\r\n  }\r\n}\r\n\r\nFuture\u003cvoid\u003e testAutomaticReload() async {\r\n  log.info(\u0027TEST: test_automatic_reload...\u0027);\r\n\r\n  final reloaded \u003d new Completer\u003cvoid\u003e();\r\n  final hotreloader \u003d await HotReloader.create(\r\n    debounceInterval: Duration.zero, //\r\n    onAfterReload: (ctx) {\r\n      if (!reloaded.isCompleted) reloaded.complete();\r\n    }\r\n  );\r\n\r\n  try {\r\n    assert(reloadable.testfunc() \u003d\u003d \u0027foo\u0027);\r\n    await _writeReloadableDartFile(\"String testfunc() \u003d\u003e \u0027bar\u0027;\");\r\n\r\n    // wait for automatic code reload\r\n    await reloaded.future;\r\n    assert(reloadable.testfunc() \u003d\u003d \u0027bar\u0027);\r\n  } finally {\r\n    // restore initial state\r\n    await _writeReloadableDartFile();\r\n    assert(await hotreloader.reloadCode() \u003d\u003d HotReloadResult.Succeeded);\r\n    assert(reloadable.testfunc() \u003d\u003d \u0027foo\u0027);\r\n\r\n    await hotreloader.stop();\r\n  }\r\n}\r\n"}}}Content-Length: 175
CLIENT >> {"jsonrpc":"2.0","id":"2","method":"textDocument/documentColor","params":{"textDocument":{"uri":"file:///D:/dart-hotreloader/test/hotreloader_test.dart"}}}Content-Length: 181
CLIENT >> {"jsonrpc":"2.0","id":"3","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///D:/dart-hotreloader/test/hotreloader_test.dart"}}}Content-Length: 193
CLIENT >> {"jsonrpc":"2.0","method":"workspace/didChangeWorkspaceFolders","params":{"event":{"added":[{"uri":"file:///D:/dart-hotreloader/","name":"dart-hotreloader"}],"removed":[]}}}Content-Length: 174
SERVER >> {"id":"1","jsonrpc":"2.0","result":{"capabilities":{"codeActionProvider":{"codeActionKinds":["source","source.organizeImports","source.fixAll","source.sortMembers","quickfix","refactor"]},"colorProvider":{"documentSelector":[{"language":"dart","scheme":"file"}]},"completionProvider":{"resolveProvider":true,"triggerCharacters":[".","=","(","$","\"","'","{","/",":"]},"definitionProvider":true,"documentHighlightProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[";"]},"documentRangeFormattingProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["edit.sortMembers","edit.organizeImports","edit.fixAll","edit.sendWorkspaceEdit","refactor.perform"],"workDoneProgress":true},"foldingRangeProvider":true,"hoverProvider":true,"implementationProvider":true,"referencesProvider":true,"renameProvider":{"prepareProvider":true},"selectionRangeProvider":true,"semanticTokensProvider":{"full":{"delta":false},"legend":{"tokenModifiers":["documentation","constructor","declaration","importPrefix","instance","static","escape","annotation","control","label","interpolation","void"],"tokenTypes":["annotation","keyword","class","comment","method","variable","parameter","enum","enumMember","type","source","property","namespace","boolean","number","string","function","typeParameter"]},"range":true},"signatureHelpProvider":{"retriggerCharacters":[","],"triggerCharacters":["("]},"textDocumentSync":{"change":2,"openClose":true,"willSave":false,"willSaveWaitUntil":false},"workspace":{"fileOperations":{"willRename":{"filters":[{"pattern":{"glob":"**/*.dart","matches":"file"},"scheme":"file"},{"pattern":{"glob":"**/","matches":"folder"},"scheme":"file"}]}},"workspaceFolders":{"changeNotifications":true,"supported":true}},"workspaceSymbolProvider":true},"serverInfo":{"name":"Dart SDK LSP Analysis Server","version":"2.18.2"}}}Content-Length: 179
SERVER >> Content-Type: application/vscode-jsonrpc; charset=utf-8
CLIENT >> {"jsonrpc":"2.0","id":"4","method":"textDocument/foldingRange","params":{"textDocument":{"uri":"file:///D:/dart-hotreloader/test/hotreloader_test.dart"}}}Content-Length: 352
SERVER >> {"id":1,"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///D:/workspaces/projects/dart-hotreloader","section":"dart"},{"section":"dart"}]}}Content-Length: 179
SERVER >> Content-Type: application/vscode-jsonrpc; charset=utf-8
CLIENT >> {"jsonrpc":"2.0","id":1,"result":[{"completeFunctionCalls":true,"enableSdkFormatter":true,"enableSnippets":true,"lineLength":120,"renameFilesWithClasses":"prompt","updateImportsOnRename":true},{"completeFunctionCalls":true,"enableSdkFormatter":true,"enableSnippets":true,"lineLength":80,"renameFilesWithClasses":"prompt","updateImportsOnRename":true}]}Content-Length: 352
SERVER >> {"id":2,"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///D:/workspaces/projects/dart-hotreloader","section":"dart"},{"section":"dart"}]}}Content-Length: 213
SERVER >> Content-Type: application/vscode-jsonrpc; charset=utf-8
CLIENT >> {"jsonrpc":"2.0","id":2,"result":[{"completeFunctionCalls":true,"enableSdkFormatter":true,"enableSnippets":true,"lineLength":120,"renameFilesWithClasses":"prompt","updateImportsOnRename":true},{"completeFunctionCalls":true,"enableSdkFormatter":true,"enableSnippets":true,"lineLength":80,"renameFilesWithClasses":"prompt","updateImportsOnRename":true}]}Content-Length: 38
SERVER >> {"id":3,"jsonrpc":"2.0","method":"client/registerCapability","params":{"registrations":[{"id":"0","method":"textDocument/formatting","registerOptions":{"documentSelector":[{"language":"dart","scheme":"file"}]}}]}}Content-Length: 47
SERVER >> Content-Type: application/vscode-jsonrpc; charset=utf-8
SERVER >> {"id":"3","jsonrpc":"2.0","result":{"data":[]}}Content-Length: 38
SERVER >> Content-Type: application/vscode-jsonrpc; charset=utf-8
```

**Comment by wesleybl** [comment]
@vrubezhny the [CSS server](https://github.com/eclipse/wildwebdeveloper/tree/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css) seems to work. Perhaps this could give a clue as to why ESLint is not working.

**Comment by wesleybl** [comment]
@vrubezhny I did the test of putting the [CSS server path](https://github.com/eclipse/wildwebdeveloper/blob/24d537e5b6dcab5d00ee9bb479bb169ed5cfa3c9/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/css/CSSLanguageServer.java#L45) on the [ESLint server](https://github.com/eclipse/wildwebdeveloper/blob/bb6a2b7a9e83d9b1903ff616d741649a7a43d903/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/eslint/ESLintLanguageServer.java#L31). With that, ESLint's client configuration method was called. So it looks like it's some incompatibility of the ESLint server with the new version of lsp4e.

**Comment by mickaelistria** [comment]
Looking at the language server logs of TestESLint, I see that `didOpen` is never sent by LSP4E to the language server; and obviously, when debugging the Language Server, we see that the `didOpen` handler is never called, nothing happens.
So it's indeed a regression of LSP4E that causes that the document is not recognized as being open. I'll move to the LSP4E issue to add more details.

**Comment by mickaelistria** [comment]
This is a combination of changes, the main one being https://github.com/eclipse/lsp4e/commit/87eae490bfa33c3e879cc6513ed100026fe867e9 which makes that the document is not "connected" to the language server. It's some optimization that was implemented, but it causes a regression when the LS doesn't participate in anything beyond reporting diagnostics.
As there is no capability for diagnostics, I think one possible remediation is to always connect document with related language servers; whenever some LS query is about to be sent.

**Comment by mickaelistria** [comment]
The issue is not this particular commit; but the fact that during documentSetup, `LanguageServers.forDocument(document)` seems to return no language servers.

**Comment by mickaelistria** [comment]
See proposed workaround in #565

**Comment by sebthom** [comment]
@mickaelistria are you planning a bug fix release for this?

**Comment by wesleybl** [comment]
> @mickaelistria are you planning a bug fix release for this?

Would it be good to have a release, otherwise, will we spend 3 months without the fix?
