### ISSUE TITLE
IllegalArgumentException when applying fix

### ISSUE THREAD

**Issue by ghentschke** [eclipse/lsp4e#579]
When applying a quick fix in the editor:
![image](https://user-images.githubusercontent.com/123444711/228588359-653b9315-db57-4a3c-94c1-3efea3b94c2f.png)

I get an IllegalArgumentException: 

```java
!ENTRY org.eclipse.core.jobs 4 2 2023-03-29 17:21:37.910
!MESSAGE An internal error occurred during: "apply resolution - change 'typedef struct{
…' to 'using data = struct{
…'".
!STACK 0
java.lang.IllegalArgumentException
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:572)
	at org.eclipse.lsp4e.LSPEclipseUtils.openEditor(LSPEclipseUtils.java:749)
	at org.eclipse.lsp4e.LSPEclipseUtils.openFileLocationInEditor(LSPEclipseUtils.java:708)
	at org.eclipse.lsp4e.LSPEclipseUtils.open(LSPEclipseUtils.java:624)
	at org.eclipse.lsp4e.LSPEclipseUtils.open(LSPEclipseUtils.java:610)
	at org.eclipse.lsp4e.LSPEclipseUtils.open(LSPEclipseUtils.java:606)
	at org.eclipse.lsp4e.LSPEclipseUtils.lambda$1(LSPEclipseUtils.java:866)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.eclipse.lsp4e.LSPEclipseUtils.applyWorkspaceEdit(LSPEclipseUtils.java:862)
	at org.eclipse.lsp4e.operations.codeactions.CodeActionMarkerResolution.run(CodeActionMarkerResolution.java:66)
	at org.eclipse.ui.internal.genericeditor.markers.MarkerInformationControl$1$1.run(MarkerInformationControl.java:141)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The reason is that the page returned by  `UI.getActivePage()`  in `org.eclipse.lsp4e.LSPEclipseUtils.open(String, Range)` is null

**Comment by sebthom** [comment]
Resolved by https://github.com/eclipse/lsp4e/pull/612
