### ISSUE TITLE
An NPE occured in `SemanticTokensDataStreamProcessor.getStyleRanges`

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/lsp4e#586]
The NPE is repeatedly occurring in WWD JUnit tests: https://ci.eclipse.org/wildwebdeveloper/job/Wildwebdeveloper/job/PR-1158/1/consoleText

The reason is probably the fact that an editor is closed (and the reconciled is uninstalled) during the reconciling job is being executed.

```
Exception in thread "org.eclipse.jface.text.reconciler.Reconciler" java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4e.operations.semanticTokens.SemanticTokensDataStreamProcessor.getStyleRanges(java.util.List, org.eclipse.lsp4j.SemanticTokensLegend)" because "this.semanticTokensDataStreamProcessor" is null
	at org.eclipse.lsp4e.operations.semanticTokens.SemanticHighlightReconcilerStrategy.saveStyle(SemanticHighlightReconcilerStrategy.java:183)
	at org.eclipse.lsp4e.operations.semanticTokens.VersionedSemanticTokens.apply(VersionedSemanticTokens.java:40)
	at org.eclipse.lsp4e.operations.semanticTokens.SemanticHighlightReconcilerStrategy.lambda$5(SemanticHighlightReconcilerStrategy.java:260)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.eclipse.lsp4e.operations.semanticTokens.SemanticHighlightReconcilerStrategy.fullReconcile(SemanticHighlightReconcilerStrategy.java:259)
	at org.eclipse.lsp4e.operations.semanticTokens.SemanticHighlightReconcilerStrategy.reconcile(SemanticHighlightReconcilerStrategy.java:280)
	at org.eclipse.ui.internal.genericeditor.CompositeReconcilerStrategy.reconcile(CompositeReconcilerStrategy.java:63)
	at org.eclipse.jface.text.reconciler.Reconciler.process(Reconciler.java:149)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
```

**Comment by vrubezhny** [comment]
And yet another one after the first one is fixed:
```
Exception in thread "org.eclipse.jface.text.reconciler.Reconciler" java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.text.ITextViewer.getTextWidget()" because "this.viewer" is null
	at org.eclipse.lsp4e.operations.semanticTokens.SemanticHighlightReconcilerStrategy.invalidateTextPresentation(SemanticHighlightReconcilerStrategy.java:228)
	at org.eclipse.lsp4e.operations.semanticTokens.VersionedSemanticTokens.apply(VersionedSemanticTokens.java:41)
	at org.eclipse.lsp4e.operations.semanticTokens.SemanticHighlightReconcilerStrategy.lambda$5(SemanticHighlightReconcilerStrategy.java:260)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.eclipse.lsp4e.operations.semanticTokens.SemanticHighlightReconcilerStrategy.fullReconcile(SemanticHighlightReconcilerStrategy.java:259)
	at org.eclipse.lsp4e.operations.semanticTokens.SemanticHighlightReconcilerStrategy.reconcile(SemanticHighlightReconcilerStrategy.java:280)
	at org.eclipse.ui.internal.genericeditor.CompositeReconcilerStrategy.reconcile(CompositeReconcilerStrategy.java:63)
	at org.eclipse.jface.text.reconciler.Reconciler.process(Reconciler.java:149)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)
Uncaught exception received.
```
