### ISSUE TITLE
Language Server sometimes get into start/stop loop

### ISSUE THREAD

**Issue by BoykoAlex** [eclipse/lsp4e#610]
One of Spring Boot LS plugin users sometimes observes Boot LS process being started/stopped very frequently over a short period of time.
Here is the eclipse log. [metadata.zip](https://github.com/eclipse/lsp4e/files/11226192/metadata.zip )

I have noticed the chunk of the stacktrace below in the log:
```
	at java.base/java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478)
	at org.eclipse.lsp4e.LanguageServerWrapper.stop(LanguageServerWrapper.java:429)
	at org.eclipse.lsp4e.LanguageServerWrapper.start(LanguageServerWrapper.java:250)
	at org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:698)
	at org.eclipse.lsp4e.LanguageServers$LanguageServerDocumentExecutor.filter(LanguageServers.java:263)
```
My only guess therefore is that `LanguageServerWrapper.start()` is called once and then again before `isActive()` starts returning `true`, i.e. before `launcherFuture` is initialized. This triggers `stop()` (from the body of the `start()` method before LS is initialized and connected to the IDE client. I'd check `isActive() || (this.initializeFuture != null && !this.initializeFuture.isDone() && !this.initializeFuture.isCancelled())` rather then just `isActive()`.

See https://github.com/spring-projects/sts4/issues/925

**Comment by BoykoAlex** [comment]
Should be fixed
