### ISSUE TITLE
null argument:Dynamic capability registration failed! Server not yet initialized?

### ISSUE THREAD

**Issue by vgcpge** [eclipse/lsp4e#617]
LanguageServerWrapper logs an error if the first message from the server is `client/registerCapability` instead of `initialize` response.

Exception:
```
Apr 23, 2023 3:51:14 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: org.eclipse.core.runtime.AssertionFailedException: null argument:Dynamic capability registration failed! Server not yet initialized?
java.util.concurrent.CompletionException: org.eclipse.core.runtime.AssertionFailedException: null argument:Dynamic capability registration failed! Server not yet initialized?
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.eclipse.core.runtime.AssertionFailedException: null argument:Dynamic capability registration failed! Server not yet initialized?
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$21(LanguageServerWrapper.java:856)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eclipse.lsp4e.LanguageServerWrapper.registerCapability(LanguageServerWrapper.java:853)
	at org.eclipse.lsp4e.LanguageClientImpl.lambda$2(LanguageClientImpl.java:136)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 6 more

unhandledRejection {"code":-32603,"data":"java.util.concurrent.CompletionException: org.eclipse.core.runtime.AssertionFailedException: null argument:Dynamic capability registration failed! Server not yet initialized?\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)\nCaused by: org.eclipse.core.runtime.AssertionFailedException: null argument:Dynamic capability registration failed! Server not yet initialized?\n\tat org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)\n\tat org.eclipse.lsp4e.LanguageServerWrapper.lambda$21(LanguageServerWrapper.java:856)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.eclipse.lsp4e.LanguageServerWrapper.registerCapability(LanguageServerWrapper.java:853)\n\tat org.eclipse.lsp4e.LanguageClientImpl.lambda$2(LanguageClientImpl.java:136)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\t... 6 more\n"}
```
Protocol dump:
```
{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":54639,"rootPath":"/Users/user/eclipse/copilot/ws/runtime-Copilot/a/","rootUri":"file:///Users/user/eclipse/copilot/ws/runtime-Copilot/a/","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"undo"},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true,"configuration":true},"textDocument":{"synchronization":{"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"completionItem":{"snippetSupport":true,"documentationFormat":["markdown","plaintext"],"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"insertTextModeSupport":{"valueSet":[1,2]}}},"hover":{"contentFormat":["markdown","plaintext"]},"signatureHelp":{},"references":{},"documentHighlight":{},"documentSymbol":{"symbolKind":{"valueSet":[18,17,5,14,9,10,22,24,8,1,12,11,20,6,2,3,21,16,19,25,4,7,15,23,26,13]},"hierarchicalDocumentSymbolSupport":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{},"definition":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"resolveSupport":{"properties":["edit"]},"dynamicRegistration":true},"codeLens":{},"documentLink":{},"colorProvider":{},"rename":{"prepareSupport":true},"foldingRange":{},"selectionRange":{},"inlayHint":{}},"window":{"workDoneProgress":true,"showMessage":{},"showDocument":{"support":true}}},"clientInfo":{"name":"Eclipse SDK","version":"0.16.1.qualifier"},"trace":"off","workspaceFolders":[{"uri":"file:///Users/user/eclipse/copilot/ws/runtime-Copilot/a/","name":"a"}]}}
Output: Content-Length: 232


Output: {"jsonrpc":"2.0","method":"LogMessage","params":{"level":0,"message":"[DEBUG] [agent] [2023-04-23T11:51:14.812Z] Agent service starting","metadataStr":"[DEBUG] [agent] [2023-04-23T11:51:14.812Z]","extra":["Agent service starting"]}}
Output: Content-Length: 204


Output: {"jsonrpc":"2.0","id":0,"method":"client/registerCapability","params":{"registrations":[{"id":"9af926ca-37e6-4049-9ac5-a66d770b8d36","method":"workspace/didChangeWorkspaceFolders","registerOptions":{}}]}}Content-Length: 182


Output: {"jsonrpc":"2.0","id":"1","result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":2},"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}}}}
Input: Content-Length: 1741

{"jsonrpc":"2.0","id":0,"error":{"code":-32603,"message":"Internal error.","data":"java.util.concurrent.CompletionException: org.eclipse.core.runtime.AssertionFailedException: null argument:Dynamic capability registration failed! Server not yet initialized?\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)\nCaused by: org.eclipse.core.runtime.AssertionFailedException: null argument:Dynamic capability registration failed! Server not yet initialized?\n\tat org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)\n\tat org.eclipse.lsp4e.LanguageServerWrapper.lambda$21(LanguageServerWrapper.java:856)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.eclipse.lsp4e.LanguageServerWrapper.registerCapability(LanguageServerWrapper.java:853)\n\tat org.eclipse.lsp4e.LanguageClientImpl.lambda$2(LanguageClientImpl.java:136)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\t... 6 more\n"}}
Error: unhandledRejection {"code":-32603,"data":"java.util.concurrent.CompletionException: org.eclipse.core.runtime.AssertionFailedException: null argument:Dynamic capability registration failed! Server not yet initialized?\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)\nCaused by: org.eclipse.core.runtime.AssertionFailedException: null argument:Dynamic capability registration failed! Server not yet initialized?\n\tat org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)\n\tat org.eclipse.lsp4e.LanguageServerWrapper.lambda$21(LanguageServerWrapper.java:856)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.eclipse.lsp4e.LanguageServerWrapper.registerCapability(LanguageServerWrapper.java:853)\n\tat org.eclipse.lsp4e.LanguageClientImpl.lambda$2(LanguageClientImpl.java:136)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\t... 6 more\n"}
```

**Comment by vgcpge** [comment]
Copilot does it this way, and is arguably a very important case.

**Comment by vgcpge** [comment]
I did not, because AFAIK they do not disclose they use LSP under the hood, and do not formally provide API's.
