### ISSUE TITLE
Exception java.lang.IllegalStateException: Timer already cancelled.

### ISSUE THREAD

**Issue by rubenporras** [eclipse/lsp4e#758]
After updating to LSP4E 0.23 I got the following exception:

!ENTRY org.eclipse.core.filebuffers 4 2 2023-08-16 08:37:28.463
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.filebuffers".
!STACK 0
java.lang.IllegalStateException: Timer already cancelled.
	at java.base/java.util.Timer.sched(Timer.java:409)
	at java.base/java.util.Timer.schedule(Timer.java:205)
	at org.eclipse.lsp4e.LanguageServerWrapper.startStopTimer(LanguageServerWrapper.java:405)
	at org.eclipse.lsp4e.LanguageServerWrapper.disconnect(LanguageServerWrapper.java:637)
	at org.eclipse.lsp4e.LanguageServerWrapper$1.bufferDisposed(LanguageServerWrapper.java:117)
	at org.eclipse.core.internal.filebuffers.TextFileBufferManager$12.run(TextFileBufferManager.java:787)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.filebuffers.TextFileBufferManager.fireBufferDisposed(TextFileBufferManager.java:784)
	at org.eclipse.core.internal.filebuffers.TextFileBufferManager.disconnect(TextFileBufferManager.java:206)
	at org.eclipse.lsp4e.operations.diagnostics.LSPDiagnosticsToMarkers$1.runInWorkspace(LSPDiagnosticsToMarkers.java:181)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by rubenporras** [comment]
When this happens as part of the makers creation, a huge number of "Stop Language Server Timer" threads is created [stack.zip](https://github.com/eclipse/lsp4e/files/12356614/stack.zip)

**Comment by rubenporras** [comment]
I think it is a duplicate of https://github.com/eclipse/lsp4e/issues/644
