### ISSUE TITLE
Popup "Problem occurred" when closing projects that use faces-config.xml or persistence.xml

### ISSUE THREAD

**Issue by erik-brangs** [eclipse/lsp4e#885]
In my Eclipse 2023-09 installation at work, when I close a project that has a ``faces-config.xml`` file or a ``persistence.xml``, I get a popup with the title ``Problem Occurred`` and a text like ``'Update markers from diagnostics' has encountered a problem. Resource '$projectName/src/main/resources/META-INF/persistence.xml' does not exist``. I'm mostly using multi-module projects.

I also have stack trace for a case with ``faces-config-xml``:

```
!ENTRY org.eclipse.core.resources 4 368 2023-10-12 13:17:20.356
!MESSAGE Resource '/[redacted]/src/main/webapp/WEB-INF/faces-config.xml' does not exist.
!STACK 0
java.lang.Exception: Resource '/[redacted]/src/main/webapp/WEB-INF/faces-config.xml' does not exist.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.Resource.checkExists(Resource.java:367)
	at org.eclipse.core.internal.resources.Resource.checkAccessible(Resource.java:241)
	at org.eclipse.core.internal.resources.Resource.findMarkers(Resource.java:1031)
	at org.eclipse.lsp4e.operations.diagnostics.LSPDiagnosticsToMarkers$1.runInWorkspace(LSPDiagnosticsToMarkers.java:140)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I tried updating to Eclipse 2023-12 but that failed due to a dependency conflict that does not make sense to me.

**Comment by erik-brangs** [comment]
The problem still occurs in Eclipse 2023-12.

**Comment by mickaelistria** [comment]
@erik-brangs Can you please try submitting a PR to fix it? I suspect it's mostly a matter of adding a `resource.exists()` somewhere.

**Comment by erik-brangs** [comment]
I haven't seen this issue since upgrading to the version that contained the PR.
