### ISSUE TITLE
BadLocationException when editing a target file

### ISSUE THREAD

**Issue by laeubi** [eclipse/lsp4e#899]
I edit an PDE target file (latest i build) and getting the exception on save:

```
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.TreeLineTracker.fail(TreeLineTracker.java:1054)
	at org.eclipse.jface.text.TreeLineTracker.nodeByLine(TreeLineTracker.java:302)
	at org.eclipse.jface.text.TreeLineTracker.getLineLength(TreeLineTracker.java:1116)
	at org.eclipse.jface.text.AbstractLineTracker.getLineLength(AbstractLineTracker.java:240)
	at org.eclipse.wst.sse.core.internal.text.BasicStructuredDocument.getLineLength(BasicStructuredDocument.java:1486)
	at org.eclipse.lsp4e.LSPEclipseUtils.getLineLength(LSPEclipseUtils.java:211)
	at org.eclipse.lsp4e.LSPEclipseUtils.toOffset(LSPEclipseUtils.java:204)
	at org.eclipse.lsp4e.operations.diagnostics.LSPDiagnosticsToMarkers.getExistingMarkerFor(LSPDiagnosticsToMarkers.java:214)
	at org.eclipse.lsp4e.operations.diagnostics.LSPDiagnosticsToMarkers$1.runInWorkspace(LSPDiagnosticsToMarkers.java:158)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

system is linux.

**Comment by sebthom** [comment]
Thanks for reporting. The issue cannot be fully avoided because of the asynchronous nature of LSP. However you should see way less exceptions in the log after #1083. I am closing the ticket for now. Feel free to reopen if required.
